# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1
  codecov: codecov/codecov@3.0.0

jobs:
  codecov:
    docker:
      - image: cimg/base:stable
    steps:
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  sample:
    jobs:
      - node/test:
          version: '16.3'
      - codecov
          